# Generated by Django 5.2 on 2025-04-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('arabic_name', models.CharField(blank=True, max_length=100)),
                ('english_name', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='students_st_created_8843cc_idx')],
            },
        ),
    ]
