# Generated by Django 5.2 on 2025-04-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created'], 'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(default=2, max_length=14, unique=True, verbose_name='الرقم القومي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم بالعربي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='كود الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='student',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الجلوس'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['seat_number', 'national_id'], name='students_st_seat_nu_f7cab5_idx'),
        ),
    ]
