# Generated by Django 5.2 on 2025-04-20 09:58

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_student_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path, verbose_name='الصورة'),
        ),
    ]
