# Generated by Django 5.2 on 2025-04-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='seat_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='رقم الجلوس'),
        ),
    ]
